name: Bug report
description: Report something that isn’t working
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe the bug clearly.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide exact steps and minimal repro if possible.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Environment
      description: OS, versions, etc.
    validations:
      required: false
